export  enum PROJECTSTATUS {
    ACTIVE = 'ACTIVE',
    PLANNED = 'PLANNED',
    ONGOING = 'ONGOING',
    ONHOLD = 'ONHOLD',
    CANCELLED = 'CANCELLED',
    COMPLETED = 'COMPLETED'
}

export  enum TASKSTATUS {
    ACTIVE = 'ACTIVE',
    CANCELLED = 'CANCELLED',
    COMPLETED = 'COMPLETED'
}

export enum USERROLES {
    CUSTOMER = "CUSTOMER",
    EMPLOYEE = "EMPLOYEE",
    ADMIN = "ADMIN",
    SUPER_ADMIN = "SUPER_ADMIN",
    USER = "USER"
}
