"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.USERROLES = exports.TASKSTATUS = exports.PROJECTSTATUS = void 0;
var PROJECTSTATUS;
(function (PROJECTSTATUS) {
    PROJECTSTATUS["ACTIVE"] = "ACTIVE";
    PROJECTSTATUS["PLANNED"] = "PLANNED";
    PROJECTSTATUS["ONGOING"] = "ONGOING";
    PROJECTSTATUS["ONHOLD"] = "ONHOLD";
    PROJECTSTATUS["CANCELLED"] = "CANCELLED";
    PROJECTSTATUS["COMPLETED"] = "COMPLETED";
})(PROJECTSTATUS || (exports.PROJECTSTATUS = PROJECTSTATUS = {}));
var TASKSTATUS;
(function (TASKSTATUS) {
    TASKSTATUS["ACTIVE"] = "ACTIVE";
    TASKSTATUS["CANCELLED"] = "CANCELLED";
    TASKSTATUS["COMPLETED"] = "COMPLETED";
})(TASKSTATUS || (exports.TASKSTATUS = TASKSTATUS = {}));
var USERROLES;
(function (USERROLES) {
    USERROLES["CUSTOMER"] = "CUSTOMER";
    USERROLES["EMPLOYEE"] = "EMPLOYEE";
    USERROLES["ADMIN"] = "ADMIN";
    USERROLES["SUPER_ADMIN"] = "SUPER_ADMIN";
    USERROLES["USER"] = "USER";
})(USERROLES || (exports.USERROLES = USERROLES = {}));
