"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express = require("express");
var Middleware = require("../middleware/middleware");
var Routes = require("../../routes");
var app = express();
Middleware.configure(app);
Routes.init(app);
Middleware.initErrorHandler(app);
app.set('port', process.env.PORT || 3000);
app.set('secret', process.env.SECRET || 'superSecret');
exports.default = app;
