"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MaterialGroupsComponent = exports.reportComponent = exports.OfferTemplateComponent = exports.FagComponent = exports.MasterMaterialComponent = exports.TaskComponent = exports.EmployeeComponent = exports.ProjectComponent = exports.MaterialComponent = exports.UserComponent = exports.AuthComponent = void 0;
var AuthComponent = require("./auth/auth.controller");
exports.AuthComponent = AuthComponent;
var UserComponent = require("./user/user.controller");
exports.UserComponent = UserComponent;
var MaterialComponent = require("./materials/material.controller");
exports.MaterialComponent = MaterialComponent;
var ProjectComponent = require("./project/project.controller");
exports.ProjectComponent = ProjectComponent;
var EmployeeComponent = require("./employee/employee.controller");
exports.EmployeeComponent = EmployeeComponent;
var TaskComponent = require("./task/task.controller");
exports.TaskComponent = TaskComponent;
var MasterMaterialComponent = require("./master-material/master-material.controller");
exports.MasterMaterialComponent = MasterMaterialComponent;
var MaterialGroupsComponent = require("./material-groups/material-groups.controller");
exports.MaterialGroupsComponent = MaterialGroupsComponent;
var FagComponent = require("./fag/fag.controller");
exports.FagComponent = FagComponent;
var OfferTemplateComponent = require("./offer-template/offer-template.controller");
exports.OfferTemplateComponent = OfferTemplateComponent;
var reportComponent = require("./report/report.controller");
exports.reportComponent = reportComponent;
